[profile.default]
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@chainlink/=lib/chainlink/contracts/',
]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
